services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002" # Next.js app
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run prod:start # Use production start for container
